// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Todolist.Models;

namespace Todolist.Migrations
{
    [DbContext(typeof(ItemlistDbContext))]
    [Migration("20181106143309_1st")]
    partial class _1st
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Todolist.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aufgabe");

                    b.Property<bool>("Erledigt");

                    b.Property<int?>("ItemlistId");

                    b.Property<int>("Priorität");

                    b.Property<bool>("Verschoben");

                    b.HasKey("Id");

                    b.HasIndex("ItemlistId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Todolist.Models.Itemlist", b =>
                {
                    b.Property<int>("ItemlistId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ItemlistId");

                    b.ToTable("Itemlist");
                });

            modelBuilder.Entity("Todolist.Models.Item", b =>
                {
                    b.HasOne("Todolist.Models.Itemlist")
                        .WithMany("Items")
                        .HasForeignKey("ItemlistId");
                });
#pragma warning restore 612, 618
        }
    }
}
